MyMVCproject/MyMVCproject/Controllers/GrafikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using myfirstproject.Models.groupsiniflar;
using myfirstproject.Models.siniflar;
using MyProject.Models.siniflar;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class GrafikController : Controller
    {
        // GET: Grafik
        Context baglan = new Context();
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult GrafikOlustur()
        //{
        //    var grafikciz = new Chart(600, 600);
        //    grafikciz.AddTitle("Kategori - Ürün Stok Sayısı").AddLegend("Stok").
        //        AddSeries("Değerler", xValue: new[] { "Mobilya", "Ofis Eşyaları", "Bilgisayar" },
        //        yValues: new[] { 85, 66, 98 }).Write();
        //    return File(grafikciz.ToWebImage().GetBytes(), "image/jpeg");
        //}

        public ActionResult VisualizeUrunResult()
        { 
            return Json(Urunlistesi(),JsonRequestBehavior.AllowGet); //google chartlara ulaşabilmemiz için gerekli
        }

        public List<UrunStok> Urunlistesi()
        {
             List<UrunStok> urunler=new List<UrunStok>();
             urunler= baglan.Uruns.Select(x=>new UrunStok
             {
                  urunad=x.UrunAd,
                  stok=x.Stok

             } ).ToList();

            return urunler;
        }
    }
}

MyMVCproject/MyMVCproject/Views/Grafik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html lang="en">

<head>

    <title>Result Visualization</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizeUrunResult", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.urunad, obj.stok]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Ürün-Stok Grafiği",

                width: 1100,

                height: 700,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.PieChart(document  //chart türünü değişebilirsin

                .getElementById('Piechart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="Piechart_div"></div>
    @*butonlara tıklandığında chartın türü değişiyor
    <a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>

    <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>

    <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@

</body>

</html>