MyMVCproject/MyMVCproject/Controllers/İstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using myfirstproject.Models.siniflar;
using MyProject.Models.siniflar;
using myfirstproject.Models.groupsiniflar;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class İstatistikController : Controller
    {
        // GET: İstatistik

        Context baglan = new Context();
        public ActionResult Index()
        {
            var ToplamCari=baglan.Carilers.Count().ToString();
            ViewBag.ToplamCari=ToplamCari;

            var ToplamPersonel = baglan.Personels.Count().ToString();
            ViewBag.ToplamPersonel = ToplamPersonel;

            var ToplamDepartman = baglan.Departmans.Count().ToString();
            ViewBag.ToplamDepartman = ToplamDepartman;

            var ToplamKategori = baglan.Kategoris.Count().ToString();
            ViewBag.ToplamKategori = ToplamKategori;

            var ToplamUrun = baglan.Uruns.Count().ToString();
            ViewBag.ToplamUrun = ToplamUrun;

            var ToplamStok = baglan.Uruns.Sum(x=>x.Stok).ToString(); //Urunler tablosundaki Tüm ürünlerin stok toplamı
            ViewBag.ToplamStok = ToplamStok;

            var KritikSeviye=baglan.Uruns.Count(x=>x.Stok <= 15).ToString(); //stok sayısı 15 den az olan ürünler kritik seviyede 
            ViewBag.KritikSeviye = KritikSeviye;

            var MarkaSayisi = (from x in baglan.Uruns 
                               select x.Marka
                               ).Distinct().Count().ToString();  //Distinct tekrarsız say bir marka bir sayım
            ViewBag.MarkaSayisi = MarkaSayisi;

            var KasadakiTutar = baglan.SatisHarekets.Sum(x => x.ToplamTutar).ToString();
            ViewBag.KasadakiTutar = KasadakiTutar;

            DateTime bugun = DateTime.Today;
            var BugunSatis = baglan.SatisHarekets.Count(x => x.Tarih==bugun).ToString();  //Bugün ki satış sayisi
            ViewBag.BugunSatis = BugunSatis;

            //Satış Sayısı 0 sa kasada sıfırdır
            if (Convert.ToInt32(BugunSatis) !=0) 
            {
                var BugunKasa = baglan.SatisHarekets.Where(x => x.Tarih == bugun).Sum(x => x.ToplamTutar).ToString();
                ViewBag.BugunKasa = BugunKasa;
            }
            else { ViewBag.BugunKasa = BugunSatis; }


            var EnCokSatan = from SatisHareket in baglan.SatisHarekets
                             join Urun in baglan.Uruns on SatisHareket.UrunId equals Urun.UrunId
                             group SatisHareket by SatisHareket.Urun.UrunAd into grup
                             select new
                             {
                                 UrunAd = grup.Key,
                                 Adet = grup.Sum(x => x.Adet)
                             };
            ViewBag.EnCokSatan = EnCokSatan.OrderByDescending(x => x.Adet).ToList().FirstOrDefault().UrunAd;

            ////En fazla ürünü olan marka 
            // var enmarka=baglan.Uruns.GroupBy(x=>x.Marka).OrderByDescending(z=>z.Count()
            // ).Select(y=>y.Key).FirstOrDefault();
            ////Belirli bir üründen kaç çeşit var
            //var BuzdolabiSayisi = baglan.Uruns.Count(x => x.UrunAd == "Buzdolabı").ToString();
            ////Max fiyatli Ürünü bulmak istersek. // min istersek descending yerine ascending(z den a)
            //var MaxFiyatUruns = (from x in baglan.Uruns
            //                     orderby x.SatisFiyat descending
            //                     select x.UrunAd).FirstOrDefault();


            return View();
        }

        // End İstatik


        // Hızlı tablolar başlangıç
        public ActionResult BasicTables()  //kolay incelenebilir tablolar  
        {
            var Sorgu = from x in baglan.Carilers     //Müşteri Şeir tablosunu partial olarak yapılmadı
                        group x by x.CariSehir into g  //g grup içine dahil olucak alan
                        select new TabloGrup
                        {
                            Sehir = g.Key,  // o grubun alanı string 
                            Sayi = g.Count()  //Şehire bağlı müşteri sayısı

                        };
            return View(Sorgu.ToList());
        }

        public PartialViewResult DeprtmnPersnlPartial()
        {
            var Sorgu2 = from x in baglan.Personels
                        group x by x.Departman.DepartmanAd into g
                        select new TabloGrup2
                        {
                            Departman = g.Key,
                            PersonelSayisi = g.Count()  
                        };
            return PartialView(Sorgu2.ToList());
        }

        public PartialViewResult CarilerPartial()
        {
            var Sorgu3 = baglan.Carilers.Where(x=>x.Durum==true).ToList();
            return PartialView(Sorgu3);
        }

        public PartialViewResult UrunlerPartial()
        {
            var Sorgu4 = baglan.Uruns.Where(x => x.Durum == true).ToList();
            return PartialView(Sorgu4);
        }

        public PartialViewResult UrunMarkaPartial()
        {
            var Sorgu5 = from x in baglan.Uruns
                         group x by x.Marka into g
                         select new TabloGrup3
                         {
                             Marka = g.Key,
                             Sayi = g.Count()  //Markadaki ürün sayısı
                         };
            return PartialView(Sorgu5.ToList());
        }

        public PartialViewResult UrunKategoriPartial()
        {
            var Sorgu6 = from x in baglan.Uruns
                         group x by x.Kategori.KategoriAd into g
                         select new TabloGrup4
                         {
                             Kategori = g.Key,
                             UrunSayisi = g.Count()
                         };
            return PartialView(Sorgu6.ToList());
        }
        //Hızlı tablolar bitiş
    }
}

MyMVCproject/MyMVCproject/Views/İstatistik/BasicTables.cshtml
@model IEnumerable<myfirstproject.Models.groupsiniflar.TabloGrup>
@{
    ViewBag.Title = "BasicTables";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        

            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Hızlı Bakış Tabloları</h1>
                        </div>
                        
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">

                            @Html.Action("UrunKategoriPartial", "İstatistik")  @*PartialView gösterimi*@

                            <br />
                            @Html.Action("DeprtmnPersnlPartial", "İstatistik")  @*PartialView gösterimi*@
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                    @*<div class="card-tools"   sayfalama >
                    <ul class="pagination pagination-sm float-right">
                        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </div>*@
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body p-0">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Şehir</th>
                                                <th>Bar</th>
                                                <th style="width: 40px">Müşteri</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{ int sirano = 0;}
                                            @foreach (var x in Model)
                                            {
                                                <tr>
                                                    <td>@{sirano++;} @sirano</td>
                                                    <td>@x.Sehir</td>
                                                    <td>
                                                        @if (1 <= x.Sayi && x.Sayi < 3)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (3 <= x.Sayi && x.Sayi < 5)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                            </div>
                                                        }
                                                        @if (x.Sayi > 4)
                                                        {
                                                            <div class="progress progress-xs progress-striped active">
                                                                <div class="progress-bar bg-success" style="width:90%"></div>
                                                            </div>
                                                        }

                                                    </td>
                                                    <td>
                                                        @if (1 <= x.Sayi && x.Sayi < 3)
                                                        {
                                                            <span class="badge bg-danger">@x.Sayi</span>
                                                        }
                                                        @if (3 <= x.Sayi && x.Sayi < 5)
                                                        {
                                                            <span class="badge bg-warning">@x.Sayi</span>
                                                        }
                                                        @if (x.Sayi > 4)
                                                        {
                                                            <span class="badge bg-success">@x.Sayi</span>
                                                        }
                                                    </td>
                                                </tr>

                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->


                            @Html.Action("UrunMarkaPartial", "İstatistik")  @*PartialView gösterimi*@


                        </div>
                        <!-- /.col -->
                    </div>

                    @Html.Action("CarilerPartial", "İstatistik")  @*PartialView gösterimi*@

                    @Html.Action("UrunlerPartial", "İstatistik")  @*PartialView gösterimi*@

                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->

       

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <!--<script src="../../plugins/jquery/jquery.min.js"></script>-->
    <!-- Bootstrap 4 -->
    <!--<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>-->
    <!-- AdminLTE App -->
    <!--<script src="../../dist/js/adminlte.min.js"></script>-->
    <!-- AdminLTE for demo purposes -->
    <!--<script src="../../dist/js/demo.js"></script>-->
</body>
</html>

MyMVCproject/MyMVCproject/Views/İstatistik/CarilerPartial.cshtml
@using myfirstproject.Models.siniflar
@model List<Cariler>
<!-- /.row -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>İsim</th>
                            <th>Soyad</th>
                            <th>Şehir</th>
                            <th>Mail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                        <tr>
                            <td>@x.CariId</td>
                            <td>@x.CariAd</td>
                            <td>@x.CariSoyad</td>
                            <td>@x.CariSehir</td>
                            <td>@x.CariMail</td>
                            
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>
<!-- /.row -->

MyMVCproject/MyMVCproject/Views/İstatistik/DeprtmnPersnlPartial.cshtml
@model IEnumerable<myfirstproject.Models.groupsiniflar.TabloGrup2>

<!-- /.card  bu partial view BasicTables view da kullanılmıştır-->

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Tablosu</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departmanlar</th>
                    <th>Progress Bar</th>
                    <th style="width: 50px">Personel</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@{sirano++;} @sirano</td>
                        <td>@x.Departman</td>
                        <td>
                            @if (1 <= x.PersonelSayisi && x.PersonelSayisi < 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (3 <= x.PersonelSayisi && x.PersonelSayisi < 5)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                </div>
                            }
                            @if (x.PersonelSayisi > 4)
                            {
                                <div class="progress progress-xs progress-striped active">
                                    <div class="progress-bar bg-success" style="width:90%"></div>
                                </div>
                            }

                        </td>
                        <td>
                            @if (1 <= x.PersonelSayisi && x.PersonelSayisi < 3)
                            {
                                <span class="badge bg-danger">@x.PersonelSayisi</span>
                            }
                            @if (3 <= x.PersonelSayisi && x.PersonelSayisi < 5)
                            {
                                <span class="badge bg-warning">@x.PersonelSayisi</span>
                            }
                            @if (x.PersonelSayisi > 4)
                            {
                                <span class="badge bg-success">@x.PersonelSayisi</span>
                            }
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

MyMVCproject/MyMVCproject/Views/İstatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>
    <script src="js/zingchart.jquery.js"></script>
    <script src="js/jquery.easydropdown.js"></script>
    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.ToplamCari</h3>
                    <p>Toplam Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.ToplamPersonel</h3>
                    <p>Toplam Personel</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.ToplamDepartman</h3>
                    <p>Toplam Departman</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.ToplamKategori</h3>
                    <p>Toplam Kategori</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.ToplamUrun</h3>
                    <p>Toplam Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.ToplamStok</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.MarkaSayisi</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.KritikSeviye</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.EnCokSatan</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.KasadakiTutar</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.BugunSatis</h3>
                    <p>Bugünki Satışlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.BugunKasa</h3>
                    <p>Bugünki Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
      
</body>
</html>

MyMVCproject/MyMVCproject/Views/İstatistik/UrunKategoriPartial.cshtml
@model IEnumerable<myfirstproject.Models.groupsiniflar.TabloGrup4>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Kategori-Ürün Tablosu</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Kategori Adı</th>
                    <th>İşlem Bar</th>
                    <th style="width: 40px">Ürün</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@{sirano++;} @sirano</td>
                        <td>@x.Kategori</td>
                        <td>
                            @if (1 <= x.UrunSayisi && x.UrunSayisi < 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (3 <= x.UrunSayisi && x.UrunSayisi < 5)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                </div>
                            }
                            @if (x.UrunSayisi > 4)
                            {
                                <div class="progress progress-xs progress-striped active">
                                    <div class="progress-bar bg-success" style="width:90%"></div>
                                </div>
                            }

                        </td>
                        <td>
                            @if (1 <= x.UrunSayisi && x.UrunSayisi < 3)
                            {
                                <span class="badge bg-danger">@x.UrunSayisi</span>
                            }
                            @if (3 <= x.UrunSayisi && x.UrunSayisi < 5)
                            {
                                <span class="badge bg-warning">@x.UrunSayisi</span>
                            }
                            @if (x.UrunSayisi > 4)
                            {
                                <span class="badge bg-success">@x.UrunSayisi</span>
                            }
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    @*<div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
            </ul>
        </div>*@
</div>

MyMVCproject/MyMVCproject/Views/İstatistik/UrunMarkaPartial.cshtml
@model IEnumerable<myfirstproject.Models.groupsiniflar.TabloGrup3>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Markalar </h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Marka</th>
                    <th>Bar</th>
                    <th style="width: 40px">Ürün</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@{sirano++;} @sirano</td>
                        <td>@x.Marka</td>
                        <td>
                            @if (1 <= x.Sayi && x.Sayi < 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (3 <= x.Sayi && x.Sayi < 5)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                </div>
                            }
                            @if (x.Sayi > 4)
                            {
                                <div class="progress progress-xs progress-striped active">
                                    <div class="progress-bar bg-success" style="width:90%"></div>
                                </div>
                            }

                        </td>
                        <td>
                            @if (1 <= x.Sayi && x.Sayi < 3)
                            {
                                <span class="badge bg-danger">@x.Sayi</span>
                            }
                            @if (3 <= x.Sayi && x.Sayi < 5)
                            {
                                <span class="badge bg-warning">@x.Sayi</span>
                            }
                            @if (x.Sayi > 4)
                            {
                                <span class="badge bg-success">@x.Sayi</span>
                            }
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->