MyMVCproject/MyMVCproject/Models/siniflar/Kargo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace myfirstproject.Models.siniflar
{
    public class Kargo
    {
        [Key]
        public int KargoId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string Aciklama { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }
        public string Personel { get; set; }
        public string Alici { get; set; }
        public DateTime Tarih { get; set; }
    }
}

MyMVCproject/MyMVCproject/Models/siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace myfirstproject.Models.siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string Aciklama { get; set; }
        public DateTime Tarih { get; set; }
    }
}

MyMVCproject/MyMVCproject/Controllers/KargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using myfirstproject.Models.siniflar;
using MyProject.Models.siniflar;
using PagedList;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class KargoController : Controller
    {
        // GET: Kargo

        Context baglan = new Context();
        public ActionResult Index(string p, int sayfa = 1)
        {
            var degerler = baglan.Kargos.Where(x => x.TakipKodu.Contains(p) || p == null).ToList().ToPagedList(sayfa, 4); //kaçıncı sayfadan başlayacak , Hersayfada kaç değer olucak 
            return View(degerler);  //geriye degerleri döndür
        }

        [HttpGet]
        public ActionResult YeniKargo()
        {
            List<SelectListItem> cariler = (from x in baglan.Carilers.ToList()
                                            where x.Durum == true
                                            select new SelectListItem
                                            {
                                                Text = x.CariAd + " " + x.CariSoyad,
                                                Value = x.CariAd + " " + x.CariSoyad
                                            }).ToList();
            ViewBag.cariler = cariler;
            List<SelectListItem> personeller = (from x in baglan.Personels.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = x.PersonelAd + " " + x.PersonelSoyad,
                                                    Value = x.PersonelAd + " " + x.PersonelSoyad
                                                }).ToList();
            ViewBag.personeller = personeller;

            Random rnd= new Random(); //random sayı oluşturuyoruz
            string[] karakterler = { "A", "B", "C", "D" };
            int k1, k2, k3;
            k1 = rnd.Next(0, 4); //0-4 arası değerler alabilir
            k2 = rnd.Next(0, 4); //0-4 arası değerler alabilir
            k3 = rnd.Next(0, 4); //0-4 arası değerler alabilir
            int s1, s2, s3;
            s1= rnd.Next(100,1000); //3 karaktek gelicek
            s2= rnd.Next(10,99); //2 karakter
            s3= rnd.Next(10,99);
            string kod = s1.ToString() + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.takipkod = kod;
            return View();
        }

        [HttpPost]
        public ActionResult YeniKargo(Kargo kargo)
        {
            baglan.Kargos.Add(kargo);
            baglan.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KargoTakip(string id)
        { 
            var degerler = baglan.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            ViewBag.kod = id;
            return View(degerler);
        }
    }
}

MyMVCproject/MyMVCproject/Views/Kargo/Index.cshtml
@using myfirstproject.Models.siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList.PagedList<Kargo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />

@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>
        Kargo Takip Numarası: @Html.TextBox("p")  @*bir parametre gönderiyo p adında*@
        <input type="submit" value="Ara" />
    </p>
}
<table class="table table-striped" style="margin-top: 20px; background-color: cornsilk">
    <tr>
        <th> Takip Kodu </th>
        <th> Personel </th>
        <th> Alıcı </th>
        <th> Tarih </th>
        <th> Detaylar </th>
    </tr>

    @foreach (var k in Model)
    {
        <tr>
            <td>@k.TakipKodu</td>
            <td>@k.Personel</td>
            <td>@k.Alici</td>
            <td>@k.Tarih</td>
            <td>
                <a href="/Kargo/KargoTakip/@k.TakipKodu" class="btn btn-default" style="background-color: lightseagreen; color:white"> Detaylar </a>
            </td>
        </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa })
   , new PagedListRenderOptions
   {
       LiElementClasses = new List<string>
       { "page-link"}
   })

<a href="/Kargo/YeniKargo/" class="btn btn-info" style="background-color: firebrick"> Yeni Kargo Girişi  </a>

MyMVCproject/MyMVCproject/Views/Kargo/KargoTakip.cshtml
@using myfirstproject.Models.siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<ol class="breadcrumb mb-4">
   
    <li class="breadcrumb-item active"> Kargo Takip Kodu: @ViewBag.kod  </li>
</ol>

<table class="table table-striped" style="margin-top:20px; background-color: cornsilk">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Aciklama</td>
            <td>@x.Tarih</td>
        </tr>
    }
</table>

MyMVCproject/MyMVCproject/Views/Kargo/YeniKargo.cshtml
@model myfirstproject.Models.siniflar.Kargo

@{
    ViewBag.Title = "YeniKargo";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<br />
<h2 style=" font-size:25px ">Yeni Kargo </h2>
<br />

<form class="form-group" method="post">

    <div>
        @Html.Label("Takip Kodu")
        <input type="text" name="TakipKodu" value="@ViewBag.takipkod" class="form-control" readonly />
        <br />
        @Html.Label("Personel")
        @Html.DropDownListFor(x => x.Personel, (List<SelectListItem>)ViewBag.personeller, new { @class = "form-control" }) @*controller urunekleden dgr1 degeri geliyor.*@
        <br />
        @Html.Label("Alıcı")
        @Html.DropDownListFor(x => x.Alici, (List<SelectListItem>)ViewBag.cariler, new { @class = "form-control" })
        <br />
        @Html.Label("Açıklama")
        @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        <input type="date" name="Tarih" class="form-control" />
        <br />

        <button class="btn btn-info" id="kaydet"> Kaydet </button>
        <script>
            $('#kaydet').click(function () {
                swal("Kargo Eklendi");
            })
        </script>
    </div>
</form>